### ISSUE TITLE
switch for MLText behavior missing in 6.x patch branches

### ISSUE THREAD

**Issue by hi-ko** [ecm4u/alfresco-repository#1]
please include / port switch for MLText from 5.2 / 6.16.ecm4u.1 patch from branch
https://github.com/ecm4u/alfresco-data-model/commit/569872e1382444cb93146c819133a9a99cd0157c

**Comment by ghost** [comment]
fixed in eb90f7e3fb00f73aad74b4d70544e3ccc2ffaf54
